contact_links:
  - name: Ask a question
    url: https://github.com/ElasticBottle/scalene-lab
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/ElasticBottle/scalene-lab
    about: Feature requests should be opened as discussions
